id: P01AE290F
initial_creation_type: input
source_metadata:
  title: TYKYN
  language: fr
  volumes:
    13f623d21a904602818332270253a514:
      title: Complete text
      base_file: Complete text.txt
      work_id: WF625A2B4
  chapter_to_tile: {}
created_at: '2022-03-02T09:14:42.479275'
last_modified_at: '2022-03-02T09:14:42.479296'
